---
title: "EPPS 6354 Information Management | Spring 2026"
format: html
---

# Information Management Project

## Cosmic Trajectories \| Spring 2026

### Project Pitch \| Feb 2026

<details>

<summary><strong>Or Click to Show/Hide Pitch</strong></summary>

<iframe src="6354ProjectProposal.pdf" width="100%" height="800px" style="border: none; margin-top: 1em;">

</iframe>

</details>

### Pitch Deck \| Feb 2026

<details>

<summary><strong>Or Click to Show/Hide Pitch Deck</strong></summary>

<iframe src="6354PitchDeck.pdf" width="100%" height="800px" style="border: none; margin-top: 1em;">

</iframe>

</details>

### Progress Report I \| Mar 2026

<details>

<summary><strong>Or Click to Show/Hide Progress Report</strong></summary>

<iframe src="6354ProjectProgress.pdf" width="100%" height="800px" style="border: none; margin-top: 1em;">

</iframe>

</details>

### Progress Report II \| Apr 2026

<details>

<summary><strong>Or Click to Show/Hide Progress Report</strong></summary>

<iframe src="6354ProgressReport2.pdf" width="100%" height="800px" style="border: none; margin-top: 1em;">

</iframe>

</details>

### Shiny Application \| [Link](https://martinezjoseph0517.github.io/cosmictrajectories/Trajecta.html)

### Final Presentation \| May 2026

<details>

<summary><strong>Or Click to Show/Hide Progress Report</strong></summary>

<iframe src="6354FinalPresentation.pdf" width="100%" height="800px" style="border: none; margin-top: 1em;">

</iframe>

</details>

### Final Report \| May 2026

<details>

<summary><strong>Or Click to Show/Hide Progress Report</strong></summary>

<iframe src="6354FinalReport.pdf" width="100%" height="800px" style="border: none; margin-top: 1em;">

</iframe>

</details>

# Assignments

- [Assignment 1 - Information Management Applications - February 5th, 2026](6354-A1.qmd)

- [Assignment 2 - Relational Schema - February 12th, 2026](6354-A2.qmd)

- [Assignment 3 - SQL Queries - February 19th, 2026](6354-A3.qmd)

- [Assignment 4 - Database Modeling with SQL - February 26th, 2026](6354-A4.qmd)

- [Assignment 5 - E-R Diagrams - March 5th, 2026](6354-A5.qmd)

- [Assignment 6 - Web Data Formats - March 26th, 2026](6354-A6.qmd)

- [Assignment 7 - AI Lab - April 9th, 2026](6354-A7.qmd)

- [Assignment 8 - NBA Shiny App - April 16th, 2026](6354-A8.qmd)
